modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/SonarSonic/Flux-Networks/issues"
license="MIT"

[[mods]]
    modId="fluxnetworks"
    version="${version}"
    displayName="Flux Networks"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/flux-networks"
    authors="Sonar Sonic, BloCamLimb"
    description='''
    Wireless Energy Networks
    '''

[[dependencies.fluxnetworks]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.8,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="modernui"
    mandatory=false
    versionRange="[3.7.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fluxnetworks]]
    modId="jei"
    mandatory=false
    versionRange="[11.3.0,)"
    ordering="NONE"
    side="BOTH"
