modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/SonarSonic/Flux-Networks/issues"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/flux-networks"
    logoFile="assets/${mod_id}/icon.png"
    authors="${mod_authors}"
    description='''${mod_description}'''

#[[accessTransformers]]
#    file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    # One of "required", "optional", "incompatible" or "discouraged".
    type="required"
    # reason="..."
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="modernui"
    type="optional"
    versionRange="[3.11,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jei"
    type="optional"
    versionRange="[19,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="the_one_probe"
    type="optional"
    versionRange="[12,)"
    ordering="NONE"
    side="BOTH"

#[features.${mod_id}]
#    openGLVersion="[3.2,)"